on:
  schedule:
    - cron: "*/5 5-23 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ping Render App
        run: |
          node <<'EOF'
          const https = require("https");
          const url = "https://auth-with-express.onrender.com/";
          const now = new Date();
          const hour = now.getUTCHours();

          if (hour < 5 || hour >= 23) {
            console.log("⏸️ Skipping ping (quiet hours).");
            process.exit(0);
          }

          console.log("🕒 Current UTC time:", now.toISOString());
          const req = https.get(url, (res) => {
            console.log(`✅ Pinged ${url}, status: ${res.statusCode}`);
            res.on("data", () => {});
            res.on("end", () => process.exit(0));
          });

          req.on("error", (err) => {
            console.error("❌ Error:", err.message);
            process.exit(1);
          });
          EOF
